name: API Regression Suite CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest and generate HTML report
      run: |
        mkdir -p reports/html
        pytest tests/test_api_endpoints.py \
          --html=reports/html/report.html \
          --self-contained-html \
          -v

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: reports/html/report.html
